import type { Company } from './types';

export const mockCompanies: Company[] = [
  {
    id: 1,
    name: 'TechVision Inc',
    description:
      'Leading provider of AI and machine learning solutions for enterprises',
    industry: 'Technology',
    location: 'San Francisco',
    employees: 2500,
    founded: 2015,
    revenue: 450,
  },
  {
    id: 2,
    name: 'FinanceCore',
    description: 'Digital banking and financial services platform',
    industry: 'Finance',
    location: 'New York',
    employees: 1800,
    founded: 2012,
    revenue: 320,
  },
  {
    id: 3,
    name: 'HealthTech Global',
    description: 'Healthcare analytics and patient management systems',
    industry: 'Healthcare',
    location: 'London',
    employees: 950,
    founded: 2018,
    revenue: 180,
  },
  {
    id: 4,
    name: 'RetailHub Solutions',
    description: 'E-commerce and retail management platform',
    industry: 'Retail',
    location: 'Singapore',
    employees: 1200,
    founded: 2016,
    revenue: 220,
  },
  {
    id: 5,
    name: 'ManuFacture Pro',
    description: 'Industrial automation and smart factory solutions',
    industry: 'Manufacturing',
    location: 'Tokyo',
    employees: 3200,
    founded: 2010,
    revenue: 580,
  },
  {
    id: 6,
    name: 'CloudSync Technologies',
    description: 'Cloud infrastructure and DevOps solutions',
    industry: 'Technology',
    location: 'San Francisco',
    employees: 1500,
    founded: 2017,
    revenue: 280,
  },
  {
    id: 7,
    name: 'InvestRight Capital',
    description: 'Robo-advisory and portfolio management services',
    industry: 'Finance',
    location: 'New York',
    employees: 650,
    founded: 2019,
    revenue: 120,
  },
  {
    id: 8,
    name: 'MediCare Solutions',
    description: 'Telemedicine and remote patient care platform',
    industry: 'Healthcare',
    location: 'London',
    employees: 780,
    founded: 2020,
    revenue: 95,
  },
  {
    id: 9,
    name: 'ShopEasy Networks',
    description: 'Omnichannel retail experience platform',
    industry: 'Retail',
    location: 'Singapore',
    employees: 890,
    founded: 2017,
    revenue: 150,
  },
  {
    id: 10,
    name: 'Precision Manufacturing',
    description: 'CNC machining and precision engineering services',
    industry: 'Manufacturing',
    location: 'Tokyo',
    employees: 2100,
    founded: 2008,
    revenue: 380,
  },
  {
    id: 11,
    name: 'DataStream Analytics',
    description: 'Big data processing and business intelligence',
    industry: 'Technology',
    location: 'San Francisco',
    employees: 1100,
    founded: 2016,
    revenue: 210,
  },
  {
    id: 12,
    name: 'PaymentXpress',
    description: 'Payment processing and financial transaction services',
    industry: 'Finance',
    location: 'New York',
    employees: 920,
    founded: 2014,
    revenue: 185,
  },
  {
    id: 13,
    name: 'LabConnect Pro',
    description: 'Laboratory information management systems',
    industry: 'Healthcare',
    location: 'London',
    employees: 560,
    founded: 2019,
    revenue: 85,
  },
  {
    id: 14,
    name: 'FashionTech Dynamics',
    description: 'Smart inventory and trend forecasting for fashion',
    industry: 'Retail',
    location: 'Singapore',
    employees: 720,
    founded: 2018,
    revenue: 135,
  },
  {
    id: 15,
    name: 'Industrial Robotics Ltd',
    description: 'Robotic automation systems for manufacturing',
    industry: 'Manufacturing',
    location: 'Tokyo',
    employees: 2800,
    founded: 2009,
    revenue: 520,
  },
  {
    id: 16,
    name: 'SecureNet Systems',
    description: 'Cybersecurity and threat detection solutions',
    industry: 'Technology',
    location: 'San Francisco',
    employees: 980,
    founded: 2015,
    revenue: 195,
  },
  {
    id: 17,
    name: 'CryptoVault Financial',
    description: 'Digital asset management and blockchain services',
    industry: 'Finance',
    location: 'New York',
    employees: 580,
    founded: 2021,
    revenue: 75,
  },
  {
    id: 18,
    name: 'PharmaTech Innovations',
    description: 'Drug discovery and pharmaceutical research platform',
    industry: 'Healthcare',
    location: 'London',
    employees: 1350,
    founded: 2017,
    revenue: 255,
  },
  {
    id: 19,
    name: 'DeliveryFlow Logistics',
    description: 'Last-mile delivery and logistics optimization',
    industry: 'Retail',
    location: 'Singapore',
    employees: 1600,
    founded: 2016,
    revenue: 240,
  },
  {
    id: 20,
    name: 'BuildTech Solutions',
    description: 'Smart building and facility management systems',
    industry: 'Manufacturing',
    location: 'Tokyo',
    employees: 1450,
    founded: 2013,
    revenue: 275,
  },
  {
    id: 21,
    name: 'VisionAI Labs',
    description: 'Computer vision and image recognition technology',
    industry: 'Technology',
    location: 'San Francisco',
    employees: 780,
    founded: 2018,
    revenue: 155,
  },
  {
    id: 22,
    name: 'WealthManage Global',
    description: 'Wealth management and investment advisory services',
    industry: 'Finance',
    location: 'New York',
    employees: 2200,
    founded: 2011,
    revenue: 425,
  },
  {
    id: 23,
    name: 'DiagnosisTech',
    description: 'AI-powered medical diagnostic and imaging analysis',
    industry: 'Healthcare',
    location: 'London',
    employees: 890,
    founded: 2019,
    revenue: 165,
  },
  {
    id: 24,
    name: 'MarketPulse Analytics',
    description: 'Consumer behavior and market research intelligence',
    industry: 'Retail',
    location: 'Singapore',
    employees: 620,
    founded: 2017,
    revenue: 110,
  },
];
